version: 2.1
workflows:
  test-deploy:
    jobs:
      - hello world
jobs:
  build:
    docker:
      - image: cimg/python:3.10.0
    steps:
      - checkout
      - run: python --version
      - run: test_hello_world.py 
